
import Header from "@/components/header";
import Footer from "@/components/footer";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { FileText } from "lucide-react";

export const metadata = {
  title: "Terms of Service | Saveetha Companion",
  description: "Terms of Service for Saveetha Companion.",
};

export default function TermsPage() {
  return (
    <div className="flex min-h-screen flex-col">
      <Header />
      <main className="flex-1 pt-20 pb-12 md:py-16">
        <div className="container mx-auto max-w-3xl px-4">
            <Card className="shadow-lg">
            <CardHeader>
                <div className="flex items-center gap-3">
                    <div className="p-3 bg-primary/10 rounded-lg">
                       <FileText className="h-6 w-6 text-primary"/>
                    </div>
                    <div>
                        <CardTitle>Terms of Service</CardTitle>
                    </div>
                </div>
            </CardHeader>
            <CardContent className="prose dark:prose-invert max-w-none">
                <p>
                    By accessing and using this website, you agree to use the platform
                    responsibly and for lawful purposes only.
                </p>
                <p>
                    Users are solely responsible for the accuracy and legality of any data
                    they manually enter or upload to the platform.
                </p>
                <p>
                    This website does <strong>not guarantee accuracy</strong> of results generated by tools
                    such as calculators or planners and is provided "as-is" for reference
                    purposes only.
                </p>
                <p>
                    We reserve the right to modify or discontinue any feature at any time
                    without prior notice.
                </p>
            </CardContent>
          </Card>
        </div>
      </main>
      <Footer />
    </div>
  );
}
